version = 1

test_patterns = ["*/test/**"]

exclude_patterns = [
"public/**",
"dist/**"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ["nodejs", "mongo"]
  module_system = ["commonjs","es-modules","amd"]
  plugins = ["vue"]
