version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ["nodejs", "mongo"]
  plugins = ["vue"]

  dependency_file_path = [
  "./package.json",
  "./package-lock.json"
  ]